stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:24.0.5-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-django:
  stage: build
  image: docker:24.0.5
  script:
    - docker build -t $CI_REGISTRY_IMAGE/django-base:latest -f Dockerfile.django .
    - docker push $CI_REGISTRY_IMAGE/django-base:latest

build-nginx:
  stage: build
  image: docker:24.0.5
  script:
    - docker build -t $CI_REGISTRY_IMAGE/nginx-base:latest -f Dockerfile.nginx .
    - docker push $CI_REGISTRY_IMAGE/nginx-base:latest
